/* eslint-disable @next/next/no-html-link-for-pages -- Storybook manager links do not use the Next.js router. */
import { useState } from 'react';
import { ChevronDown, Check, CheckCircle2 } from 'lucide-react';
import { Button } from '../components/ui/button';
import { ComponentDetail } from './ReleaseCandidate';
import { formatReleaseDate } from './release-date';
import manifest from '../../design-system/release-manifest.json';
const summaryClass = 'flex cursor-pointer list-none items-center justify-between gap-4 px-5 py-4 text-sm font-medium text-card-foreground md:px-6';

export function MinorRelease() {
  const components = manifest.components.filter(item => item.release === '1.2.0');
  const [selected, setSelected] = useState<string | null>(null);
  const component = components.find(item => item.id === selected);
  return <div className="relative ml-1 border-l border-border pl-6"><span className="absolute -left-1.5 top-7 size-3 rounded-full border-2 border-background bg-primary" aria-hidden="true" />
    <details open className="group/release overflow-hidden rounded-xl border border-border bg-card">
      <summary className="flex cursor-pointer list-none items-start justify-between gap-4 px-5 py-5 md:px-6"><div className="grid gap-1"><div className="flex flex-wrap items-center gap-2"><h3 className="m-0 text-lg font-semibold">Versión {manifest.version}</h3><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-medium">Estable</span><span className="rounded-full bg-primary px-2.5 py-1 text-xs font-medium text-primary-foreground">Última publicada</span></div><p className="m-0 text-sm text-muted-foreground">Nuevas composiciones, Stepper e inspector de Storybook.</p></div><div className="flex shrink-0 items-center gap-3"><time dateTime={manifest.publishedAt} className="hidden text-sm leading-5 text-muted-foreground sm:block">{formatReleaseDate(manifest.publishedAt)}</time><ChevronDown className="size-4 shrink-0 transition-transform group-open/release:rotate-180" aria-hidden="true" /></div></summary>
      <div className="border-t border-border"><div className="grid gap-7 px-5 py-6 md:px-6"><time dateTime={manifest.publishedAt} className="text-xs leading-4 text-muted-foreground sm:hidden">{formatReleaseDate(manifest.publishedAt)}</time><div className="grid gap-5 sm:grid-cols-3">{[[String(components.length), 'Componentes'], ['4', 'Marcas'], ['1', 'Herramienta nueva']].map(([value,label])=><div key={label}><strong className="block text-sm">{value}</strong><span className="text-xs text-muted-foreground">{label}</span></div>)}</div><div><h4 className="m-0 mb-3 text-sm font-semibold">Incluye</h4><ul className="m-0 grid list-none gap-2 p-0 text-sm sm:grid-cols-2">{["Stepper como componente no legacy.", "Sheet, Item y Tabs ampliados desde Figma.", "Portales configurables en Popover y Combobox.", "Inspector global y por componente."].map(item=><li key={item} className="flex gap-2"><Check className="mt-0.5 size-4 shrink-0" aria-hidden="true" />{item}</li>)}</ul></div></div>
        <details className="border-t border-border"><summary className={summaryClass}><span>Componentes incluidos</span><span className="text-xs text-muted-foreground">{components.length} componentes</span></summary><div className="border-t border-border bg-muted/30 px-5 py-5 md:px-6"><p className="mt-0 text-sm text-muted-foreground">Selecciona un componente para consultar su actualización exacta.</p><div className="flex flex-wrap gap-2">{components.map(item=><Button key={item.id} variant="outline" size="sm" aria-label={`Ver cambios de ${item.name}`} aria-pressed={selected===item.id} aria-controls="minor-component-changes" onClick={()=>setSelected(item.id)} className={selected===item.id ? 'bg-muted text-foreground' : ''}>{item.name}</Button>)}</div><div id="minor-component-changes">{component && <ComponentDetail component={component} release={manifest.version} tokenValuesChanged={false} />}</div></div></details>
        <details className="border-t border-border"><summary className={summaryClass}>Inspector de Storybook · Nuevo</summary><div className="border-t border-border bg-muted/30 px-5 py-5 md:px-6"><p className="mt-0 text-sm">Versión inicial 1.0.0 · Herramienta de documentación incluida en la versión global 1.2.0.</p><ul className="m-0 list-disc pl-5 text-sm">{manifest.tooling[0].updates.map(update => <li key={update}>{update}</li>)}</ul></div></details><details className="border-t border-border"><summary className={summaryClass}><span>Validación de cierre</span><CheckCircle2 className="size-4" aria-hidden="true" /></summary><div className="grid gap-5 border-t border-border bg-muted/30 px-5 py-5 md:px-6"><ul className="m-0 list-disc pl-5 text-sm"><li>Validación de cierre del 2 de octubre de 2026.</li><li>97 pruebas aprobadas y 2 fallas de contraste de Stepper correspondientes a las excepciones de marca conocidas.</li><li>Variables y estilos conservan sus versiones y valores frente a 1.1.1.</li><li>TypeScript y compilación correctos. ESLint sin errores y una advertencia preexistente. Suite completa: 99 pruebas, incluido el inspector y Releases.</li><li><strong>Excepción aceptada para v1.2.0:</strong> Tabs Underline de María Linda alcanza 4.27:1 sobre el fondo de Docs, por debajo de 4.5:1. Se conserva por decisión del usuario y no bloquea este lanzamiento.</li></ul><section className="rounded-lg border border-border bg-card p-4"><h5 className="m-0 text-sm font-semibold">Excepciones de marca heredadas</h5><p className="mb-0 mt-2 text-sm"><strong>Reina Madre y Piel Sana:</strong> combinaciones de primary y brand-gradient con contraste insuficiente, incluidos los componentes que consumen esos roles. Se conservan por decisión de marca. Las excepciones no se extienden a success, warning, destructive ni otros roles.</p><p className="mb-0 mt-2 text-sm">La validación con excepciones no declara cumplimiento WCAG completo.</p></section></div></details>
        <details className="border-t border-border"><summary className={summaryClass}>Trazabilidad de versiones</summary><div className="grid gap-3 border-t border-border px-5 py-5 text-sm md:px-6"><p className="m-0">Global: <strong>1.1.1 → 1.2.0</strong>. Base de comparación: <code>{manifest.baselineCommit}</code>. Cada componente conserva su propia secuencia; su versión no tiene que coincidir con la global.</p><p className="m-0">Sheet, Item, Tabs, Popover y Combobox avanzan a 1.1.0. Stepper e Inspector inician en 1.0.0. Variables, estilos y Drawer conservan sus versiones.</p><div className="flex flex-wrap gap-4"><a className="underline" href="/r/release-history.json">Historial global</a><a className="underline" href="/r/release-manifest.json">Versiones por componente, variable y estilo</a><a className="underline" href="/r/figma-snapshot.json">Snapshot de Figma</a><a className="underline" target="_top" href="/?path=/docs/foundations-tokens--docs">Cambios de tokens</a></div></div></details>
      </div>
    </details>
  </div>;
}
