import { formatReleaseDate } from './release-date';
/* eslint-disable @next/next/no-html-link-for-pages -- Storybook manager links do not use the Next.js router. */
import { useState } from 'react';
import { ChevronDown, Check, CheckCircle2 } from 'lucide-react';
import { Button } from '../components/ui/button';
import manifest from '../../docs/releases/1.1.0/published-manifest.json';

type ComponentChange = typeof manifest.components[number];
const summaryClass = 'flex cursor-pointer list-none items-center justify-between gap-4 px-5 py-4 text-sm font-medium text-card-foreground md:px-6';

export function ComponentDetail({ component, release = manifest.version }: { component: ComponentChange; release?: string }) {
  return <section aria-label={`Cambios de ${component.name}`} className="mt-5 grid gap-5 rounded-lg border border-border bg-card p-5">
    <header><h5 className="m-0 text-base font-semibold">{component.name} · v{component.previousVersion} → v{component.version}</h5><p className="mb-0 mt-2 text-sm">{component.change}</p></header>
    <div className="grid gap-4 sm:grid-cols-2"><div><strong className="text-sm">Variantes nuevas</strong><p className="mb-0 mt-1 text-sm">{component.newVariants.join(', ') || 'Ninguna.'}</p></div><div><strong className="text-sm">Composiciones nuevas</strong><p className="mb-0 mt-1 text-sm">{component.newCompositions.join(', ') || 'Ninguna.'}</p></div></div>
    <ul className="m-0 list-disc pl-5 text-sm">{component.updates.map(update => <li key={update}>{update}</li>)}</ul>
    <p className="m-0 text-xs text-muted-foreground">Trayectoria documentada: {[...component.history].reverse().map(item => `v${item.version}`).join(' → ')}. Versión global de esta actualización: v{release}.</p>
    <a className="text-sm underline underline-offset-4" target="_top" href={`/?path=/docs/components-${component.id}--docs`}>Ver documentación e historial de {component.name}</a>
    <div className="grid gap-3">
      <h6 className="m-0 text-sm font-semibold">Tokens afectados</h6>
      <ul className="m-0 flex list-none flex-wrap gap-2 p-0">{component.affectedSemanticRoles.map(role => <li key={role} className="rounded border border-border bg-muted px-2 py-1"><code className="break-words text-xs">{role}</code></li>)}</ul>
      <a className="text-sm underline underline-offset-4" target="_top" href="/?path=/docs/foundations-tokens--docs">Consultar valores anteriores y actuales por marca en Tokens</a>
    </div>
  </section>;
}

export function ReleaseCandidate() {
  const [selected, setSelected] = useState<string | null>(null);
  const component = manifest.components.find(item => item.id === selected);
  return <div className="relative ml-1 border-l border-border pl-6"><span className="absolute -left-1.5 top-7 size-3 rounded-full border-2 border-background bg-foreground" aria-hidden="true" />
    <details className="group/release overflow-hidden rounded-xl border border-border bg-card">
      <summary className="flex cursor-pointer list-none items-start justify-between gap-4 px-5 py-5 md:px-6"><div className="grid gap-1"><div className="flex flex-wrap items-center gap-2"><h3 className="m-0 text-lg font-semibold">Versión {manifest.version}</h3><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-medium">Estable</span></div><p className="m-0 text-sm text-muted-foreground">Actualización de tokens, estilos y componentes con excepciones de contraste documentadas.</p></div><div className="flex shrink-0 items-center gap-3"><time dateTime={manifest.publishedAt} className="hidden text-sm leading-5 text-muted-foreground sm:block">{formatReleaseDate(manifest.publishedAt)}</time><ChevronDown className="size-4 shrink-0 transition-transform group-open/release:rotate-180" aria-hidden="true" /></div></summary>
      <div className="border-t border-border"><div className="grid gap-7 px-5 py-6 md:px-6"><time dateTime={manifest.publishedAt} className="text-xs leading-4 text-muted-foreground sm:hidden">{formatReleaseDate(manifest.publishedAt)}</time><div className="grid gap-5 sm:grid-cols-3">{[[String(manifest.components.length), 'Componentes'], ['4', 'Marcas'], ['Vercel', 'Distribución']].map(([value,label])=><div key={label}><strong className="block text-sm">{value}</strong><span className="text-xs text-muted-foreground">{label}</span></div>)}</div><div><h4 className="m-0 mb-3 text-sm font-semibold">Incluye</h4><ul className="m-0 grid list-none gap-2 p-0 text-sm sm:grid-cols-2">{['769 variables y 632 valores semánticos CSS.', '40 estilos tipográficos y 12 estilos visuales.', 'Variantes, estados y contraste actualizados.', 'Versiones independientes y cambios trazables.'].map(item=><li key={item} className="flex gap-2"><Check className="mt-0.5 size-4 shrink-0" aria-hidden="true" />{item}</li>)}</ul></div></div>
        <details className="border-t border-border"><summary className={summaryClass}><span>Componentes incluidos</span><span className="text-xs text-muted-foreground">{manifest.components.length} componentes</span></summary><div className="border-t border-border bg-muted/30 px-5 py-5 md:px-6"><p className="mt-0 text-sm text-muted-foreground">Selecciona un componente para consultar su actualización exacta.</p><div className="flex flex-wrap gap-2">{manifest.components.map(item=><Button key={item.id} variant="outline" size="sm" aria-label={`Ver cambios de ${item.name}`} aria-pressed={selected===item.id} aria-controls="release-component-changes" onClick={()=>setSelected(item.id)} className={selected===item.id ? 'bg-muted text-foreground' : ''}>{item.name}</Button>)}</div><div id="release-component-changes">{component && <ComponentDetail component={component} />}</div></div></details>
        <details className="border-t border-border"><summary className={summaryClass}><span>Validación de cierre</span><CheckCircle2 className="size-4" aria-hidden="true" /></summary><div className="grid gap-5 border-t border-border bg-muted/30 px-5 py-5 md:px-6"><ul className="m-0 list-disc pl-5 text-sm"><li>TypeScript y compilación de Storybook correctos.</li><li>ESLint sin errores; una advertencia preexistente en el escáner archivado.</li><li>204 pruebas de componentes y 5 pruebas de Foundations aprobadas; Selección y detalle de los 50 componentes comprobados en Releases.</li><li>204 vistas revisadas, 24 combinaciones de Toast y 20 estados hover.</li><li>Figma y código conciliados; sin fallos de contraste fuera de las excepciones aceptadas.</li></ul><section className="rounded-lg border border-border bg-card p-4"><h5 className="m-0 text-sm font-semibold">Excepciones de marca pendientes · 28 casos</h5><p className="mb-0 mt-2 text-sm"><strong>Reina Madre y Piel Sana:</strong> combinaciones de primary y brand-gradient con contraste insuficiente, incluidos los componentes que consumen esos roles. Se conservan por decisión de marca. Las excepciones no se extienden a success, warning, destructive ni otros roles.</p><p className="mb-0 mt-2 text-sm">La validación con excepciones no declara cumplimiento WCAG completo.</p></section></div></details>
        <details className="border-t border-border"><summary className={summaryClass}>Trazabilidad de versiones</summary><div className="grid gap-3 border-t border-border px-5 py-5 text-sm md:px-6"><p className="m-0">Global: <strong>1.0.0 → 1.1.0</strong>. Base de comparación: <code>{manifest.baselineCommit}</code>. Cada componente conserva su propia secuencia; su versión no tiene que coincidir con la global.</p><p className="m-0">Variables y estilos se identifican por ID de Figma y huella. Su primer registro individual es 1.1.0; una versión anterior nula significa «sin registro previo», no «elemento nuevo». Los cambios desde 1.0.0 se consultan en Tokens.</p><div className="flex flex-wrap gap-4"><a className="underline" href="/r/release-history.json">Historial global</a><a className="underline" href="/r/release-manifest.json">Versiones por componente, variable y estilo</a><a className="underline" href="/r/figma-snapshot.json">Snapshot de Figma</a><a className="underline" target="_top" href="/?path=/docs/foundations-tokens--docs">Cambios de tokens</a></div></div></details>
      </div>
    </details>
  </div>;
}
