import json,re,hashlib,html
from pathlib import Path
R=Path('/Users/miguelarias/DEV/REINA MADRE/ds-grm-documentation');D=Path(__file__).parent
old=json.load(open(D.parent/'storybook-contraste-actual/evidencia.json'));live=json.load(open(D/'browser.json'))
src=(R/'src/foundations/semantic-brand-token-values.ts').read_text();tokens=json.loads(src.split('=',1)[1].rsplit('as const;',1)[0])
def rgb(s):
 if s.startswith('#'):return [int(s[i:i+2],16) for i in (1,3,5)]
 return [float(n) for n in re.findall(r'[\d.]+',s)][:3]
def lum(c):return sum(w*(x/255/12.92 if x/255<=.04045 else ((x/255+.055)/1.055)**2.4) for w,x in zip([.2126,.7152,.0722],c))
def ratio(a,b):return (max(lum(a),lum(b))+.05)/(min(lum(a),lum(b))+.05)
def token(s):return '--'+s.split(' → ')[0].replace('/','-').replace('%','')
def gradient(b):
 a=rgb(tokens[b]['--button-brand-gradient-1']);z=rgb(tokens[b]['--button-brand-gradient-2']);return min(ratio([255]*3,[x*(1-i/1000)+y*i/1000 for x,y in zip(a,z)]) for i in range(1001))
rows=[]
for i,f in enumerate(old['findings']):
 b=f['brand'];fg=token(f['fgToken']);bg=token(f['bgToken']);isgrad=f['kind']=='gradient';exception=b in ['reina-madre','piel-sana'] and (bg.startswith('--primary') or isgrad)
 current=gradient(b) if isgrad else ratio(rgb(tokens[b][fg]),rgb(tokens[b][bg]))
 rows.append(dict(id=i,brand=b,component=f['component'],title=f['title'],state=f['state'],variant=f['variant'],threshold=f['threshold'],previousRatio=f['ratio'],ratio=current,status='passed' if current>=f['threshold'] else 'accepted-exception' if exception else 'failed',exceptionScope=exception,foreground='white' if isgrad else fg,background=['--button-brand-gradient-1','--button-brand-gradient-2'] if isgrad else bg,fg='#ffffff' if isgrad else tokens[b][fg],bg=('linear-gradient(135deg, '+tokens[b]['--button-brand-gradient-1']+', '+tokens[b]['--button-brand-gradient-2']+')') if isgrad else tokens[b][bg]))
states=[]
for b,v in tokens.items():
 for kind in ['primary','secondary','success','warning','destructive']:
  role=kind if kind in ['primary','secondary'] else kind+'-light';fg='--'+(kind+'-foreground' if kind in ['primary','secondary'] else role+'-foreground')
  for state in ['normal','hover','active']:
   bg='--'+role+('' if state=='normal' else '-'+state);cr=ratio(rgb(v[fg]),rgb(v[bg]));states.append(dict(brand=b,role=role,state=state,foreground=fg,background=bg,ratio=cr,status='passed' if cr>=4.5 else 'accepted-exception' if b in ['reina-madre','piel-sana'] and kind=='primary' else 'failed'))
renderedFailures=[]
for r in live['playgrounds']:
 for x in r['rows']:
  if x['ratio']<x['threshold']:
   exception=r['brand'] in ['reina-madre','piel-sana'] and 'bg-primary' in x['className'] and x['color']=='rgb(255, 255, 255)'
   renderedFailures.append(dict(brand=r['brand'],id=r['id'],text=x['text'],ratio=x['ratio'],status='accepted-exception' if exception else 'failed'))
review=dict(capturedAt=live['capturedAt'],status='reviewed-with-exceptions',sourceReport=str(D.parent/'storybook-contraste-actual/INFORME.html'),snapshotSha256=hashlib.sha256((R/'design-system/figma-snapshot.json').read_bytes()).hexdigest(),sourceReportSha256=hashlib.sha256((D.parent/'storybook-contraste-actual/evidencia.json').read_bytes()).hexdigest(),exceptions={'brands':['reina-madre','piel-sana'],'roles':['primary','primary-hover','primary-active','button/brand-gradient-1','button/brand-gradient-2'],'reason':'Decisión explícita del usuario: conservar primary y gradientes de esas marcas. No constituye cumplimiento WCAG.'},reportCases=rows,buttonStates=states,renderedFailures=renderedFailures,counts=dict(playgrounds=len(live['playgrounds']),storyTestRuns=204,semanticValues=sum(x['count'] for x in live['tokenParity']),reportCases=len(rows),passed=sum(r['status']=='passed' for r in rows),acceptedExceptions=sum(r['status']=='accepted-exception' for r in rows),unexpectedFailures=sum(r['status']=='failed' for r in rows+states+renderedFailures)),limits=['Contraste de los escenarios de INFORME.html y textos visibles de Playground; no certificación integral WCAG.','Estados active calculados con tokens usados por las reglas CSS; normal y hover contrastados con muestras renderizadas.','Gradientes: mínimo conservador de 1001 muestras sRGB sobre todo el fondo, no solo bajo la etiqueta.','El conector de pruebas reporta éxito incluso en excepciones confirmadas; su resultado no sustituye la medición de contraste.'])
(D/'summary.json').write_text(json.dumps(review,ensure_ascii=False,indent=2));print(json.dumps(review['counts']));print('state failures',json.dumps([x for x in states if x['status']=='failed']))
snapshot=json.load(open(R/'design-system/figma-snapshot.json'));variables={v[1]:v for v in snapshot['variables']};proposals=[]
for brand,role,palette,level in [('grm-global','destructive-light','GRM Global/status/destructive',700),('reina-madre','warning-light','Reina Madre/status/warning',900)]:
 item=next(x for x in states if x['brand']==brand and x['role']==role and x['state']=='active');value=next(iter(variables[f'{palette}/{level}'][4].values()));c=[value[k]*255 for k in ['r','g','b']];proposed='rgb('+', '.join(str(x) for x in c)+')';bg=tokens[brand][item['background']];fg=tokens[brand][item['foreground']];proposals.append({**item,'currentColor':fg,'backgroundColor':bg,'proposedToken':f'{palette}/{level}','proposedColor':proposed,'proposedRatio':ratio(c,rgb(bg)),'applied':False})
review['proposals']=proposals;review['status']='blocked-unexpected-contrast' if review['counts']['unexpectedFailures'] else 'reviewed-with-exceptions';(D/'summary.json').write_text(json.dumps(review,ensure_ascii=False,indent=2))
esc=lambda x:html.escape(str(x),quote=True)
cards=''
for p in proposals:
 cards+=f'''<article><h3>{esc(old['brands'][p['brand']])} · Button {esc(p['role'].replace('-light',''))} · active</h3><p><b>Hallazgo:</b> {p['ratio']:.4f}:1. Mínimo: 4,5:1.</p><p><b>Causa:</b> el fondo active se oscurece y el texto conserva un tono que pierde contraste.</p><div class="pair"><div><h4>Actual</h4><span class="sample" style="color:{esc(p['currentColor'])};background:{esc(p['backgroundColor'])}">Confirmar acción</span><p><code>{esc(p['foreground'])}</code><br>{esc(p['currentColor'])}<br>sobre <code>{esc(p['background'])}</code><br>{esc(p['backgroundColor'])}</p></div><div><h4>Propuesta · no aplicada</h4><span class="sample" style="color:{esc(p['proposedColor'])};background:{esc(p['backgroundColor'])}">Confirmar acción</span><p><code>{esc(p['proposedToken'])}</code><br>{esc(p['proposedColor'])}<br><b>{p['proposedRatio']:.4f}:1</b></p></div></div><p><b>Posible solución:</b> asociar {esc(p['foreground'])} al tono existente indicado. Conserva el fondo, los 500 y la familia cromática. Revalidar normal/hover/active y consumidores antes de aplicar.</p></article>'''
trs=''.join(f"<tr><td>{esc(old['brands'][r['brand']])}</td><td>{esc(r['title'])} · {esc(r['state'])}</td><td><code>{esc(r['foreground'])}</code><br><code>{esc(r['background'])}</code></td><td>{r['ratio']:.4f}:1</td><td>{'Cumple' if r['status']=='passed' else 'Excepción de producto · falla WCAG' if r['status']=='accepted-exception' else 'Pendiente'}</td></tr>" for r in rows)
page=f'''<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Validación v1.1.0 · 23 septiembre</title><style>body{{font:16px/1.5 system-ui,sans-serif;background:#f5f5f5;color:#202124;margin:0}}main{{max-width:1150px;margin:auto;padding:32px}}article,header,section{{background:white;border:1px solid #ccc;border-radius:12px;padding:24px;margin-bottom:24px}}h1{{margin-top:0}}.pair{{display:grid;grid-template-columns:1fr 1fr;gap:24px}}.sample{{display:inline-block;padding:10px 20px;border-radius:6px;font:500 14px/20px system-ui}}code{{overflow-wrap:anywhere;font-size:13px}}table{{border-collapse:collapse;width:100%;font-size:14px}}td,th{{padding:12px;text-align:left;border-bottom:1px solid #ccc}}.scroll{{overflow:auto}}@media(max-width:650px){{.pair{{grid-template-columns:1fr}}main{{padding:12px}}}}</style><main><header><h1>v1.1.0 · revisión final</h1><p><b>Lanzamiento bloqueado por 2 contrastes fuera de las excepciones.</b></p><p>23 septiembre 2026 · Figma conciliado · 204 Playground revisados · 628 valores CSS sin diferencias.</p><p>Del INFORME.html original: <b>25 casos corregidos y 28 excepciones conservadas</b>. Las excepciones corresponden exclusivamente a primary y brand-gradient de Reina Madre y Piel Sana. No equivalen a cumplimiento WCAG.</p></header><h2>Dos pendientes adicionales</h2>{cards}<section><h2>Validación y alcance</h2><p>51 stories ejecutadas por cada marca (204 resultados de éxito informados por Storybook). La medición independiente detecta los fallos de contraste que esas pruebas no reportan. Estados active calculados a partir de las reglas reales de Button y los tokens vigentes; las muestras anteriores ilustran esos pares, no son capturas del botón presionado.</p><p>Se inspeccionaron visualmente las muestras de Button de las cuatro marcas. La revisión no certifica todos los criterios WCAG ni todas las composiciones posibles. Gradientes: mínimo conservador de 1001 muestras sRGB a lo largo de todo el fondo. No se modificó Figma ni los tonos excluidos.</p><p>Referencia: <a href="https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html">WCAG 2.2 · contraste mínimo</a> y <a href="https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast.html">contraste no textual</a>.</p></section><section><h2>Los 53 casos del informe original, recalculados</h2><details><summary>Ver resultado y tokens por componente</summary><div class="scroll"><table><thead><tr><th>Marca</th><th>Componente / estado</th><th>Tokens actuales</th><th>Contraste</th><th>Resultado</th></tr></thead><tbody>{trs}</tbody></table></div></details></section></main></html>'''
(D/'INFORME.html').write_text(page)
print([(p['brand'],p['proposedToken'],p['proposedRatio']) for p in proposals])
