export const typographyStyles = [
  {
    "name": "display/one/extrabold",
    "family": "Inter",
    "fontStyle": "Extra Bold",
    "size": 30,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "TITLE",
    "textDecoration": "NONE",
    "familyToken": "typography/heading",
    "sizeToken": "text/display-1",
    "weightToken": "typography/style/extrabold",
    "lineHeightToken": ""
  },
  {
    "name": "heading/one/semibold",
    "family": "Inter",
    "fontStyle": "Semi Bold",
    "size": 24,
    "lineHeight": "Auto",
    "letterSpacing": "-2.5%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/heading",
    "sizeToken": "text/heading-1",
    "weightToken": "typography/style/semibold",
    "lineHeightToken": ""
  },
  {
    "name": "heading/one/bold",
    "family": "Inter",
    "fontStyle": "Bold",
    "size": 24,
    "lineHeight": "Auto",
    "letterSpacing": "-2.5%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/heading",
    "sizeToken": "text/heading-1",
    "weightToken": "typography/style/bold",
    "lineHeightToken": ""
  },
  {
    "name": "heading/two/semibold",
    "family": "Inter",
    "fontStyle": "Semi Bold",
    "size": 20,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/heading",
    "sizeToken": "text/heading-2",
    "weightToken": "typography/style/semibold",
    "lineHeightToken": ""
  },
  {
    "name": "heading/two/bold",
    "family": "Inter",
    "fontStyle": "Bold",
    "size": 20,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/heading",
    "sizeToken": "text/heading-2",
    "weightToken": "typography/style/bold",
    "lineHeightToken": ""
  },
  {
    "name": "heading/three/semibold",
    "family": "Inter",
    "fontStyle": "Semi Bold",
    "size": 18,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/heading",
    "sizeToken": "text/heading-3",
    "weightToken": "typography/style/semibold",
    "lineHeightToken": ""
  },
  {
    "name": "heading/three/bold",
    "family": "Inter",
    "fontStyle": "Bold",
    "size": 18,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/heading",
    "sizeToken": "text/heading-3",
    "weightToken": "typography/style/bold",
    "lineHeightToken": ""
  },
  {
    "name": "body/base/regular",
    "family": "Inter",
    "fontStyle": "Regular",
    "size": 16,
    "lineHeight": "24px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-base",
    "weightToken": "typography/style/normal",
    "lineHeightToken": ""
  },
  {
    "name": "body/base/medium",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 16,
    "lineHeight": "24px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-base",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "body/base/semibold",
    "family": "Inter",
    "fontStyle": "Semi Bold",
    "size": 16,
    "lineHeight": "24px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-base",
    "weightToken": "typography/style/semibold",
    "lineHeightToken": ""
  },
  {
    "name": "body/two/regular",
    "family": "Inter",
    "fontStyle": "Regular",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-1",
    "weightToken": "typography/style/normal",
    "lineHeightToken": ""
  },
  {
    "name": "body/two/regular uppercase",
    "family": "Inter",
    "fontStyle": "Regular",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "UPPER",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-1",
    "weightToken": "typography/style/normal",
    "lineHeightToken": ""
  },
  {
    "name": "body/two/mono-regular",
    "family": "JetBrains Mono",
    "fontStyle": "Regular",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/mono",
    "sizeToken": "text/body-1",
    "weightToken": "typography/style/normal",
    "lineHeightToken": ""
  },
  {
    "name": "body/three/regular",
    "family": "Inter",
    "fontStyle": "Regular",
    "size": 12,
    "lineHeight": "16px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-2",
    "weightToken": "typography/style/normal",
    "lineHeightToken": ""
  },
  {
    "name": "body/three/regular uppercase",
    "family": "Inter",
    "fontStyle": "Regular",
    "size": 12,
    "lineHeight": "16px",
    "letterSpacing": "2.5%",
    "textCase": "UPPER",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-2",
    "weightToken": "typography/style/normal",
    "lineHeightToken": ""
  },
  {
    "name": "body/three/medium",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 12,
    "lineHeight": "16px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-2",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "body/three/semibold",
    "family": "Inter",
    "fontStyle": "Semi Bold",
    "size": 12,
    "lineHeight": "16px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-2",
    "weightToken": "typography/style/semibold",
    "lineHeightToken": ""
  },
  {
    "name": "body/three/semibold uppercase",
    "family": "Inter",
    "fontStyle": "Semi Bold",
    "size": 12,
    "lineHeight": "16px",
    "letterSpacing": "0%",
    "textCase": "UPPER",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-2",
    "weightToken": "typography/style/semibold",
    "lineHeightToken": ""
  },
  {
    "name": "body/three/medium uppercase",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 12,
    "lineHeight": "16px",
    "letterSpacing": "2.5%",
    "textCase": "UPPER",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-2",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "caption/one/regular",
    "family": "Inter",
    "fontStyle": "Regular",
    "size": 11,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/caption-1",
    "weightToken": "typography/style/normal",
    "lineHeightToken": ""
  },
  {
    "name": "caption/one/medium",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 11,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/caption-1",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "caption/one/semibold",
    "family": "Inter",
    "fontStyle": "Semi Bold",
    "size": 11,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/caption-1",
    "weightToken": "typography/style/semibold",
    "lineHeightToken": ""
  },
  {
    "name": "caption/one/bold uppercase",
    "family": "Inter",
    "fontStyle": "Bold",
    "size": 11,
    "lineHeight": "Auto",
    "letterSpacing": "10%",
    "textCase": "UPPER",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/caption-1",
    "weightToken": "typography/style/bold",
    "lineHeightToken": ""
  },
  {
    "name": "caption/two/regular",
    "family": "Inter",
    "fontStyle": "Regular",
    "size": 10,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/caption-2",
    "weightToken": "typography/style/normal",
    "lineHeightToken": ""
  },
  {
    "name": "caption/two/medium",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 10,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/caption-2",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "caption/two/medium uppercase",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 10,
    "lineHeight": "Auto",
    "letterSpacing": "5%",
    "textCase": "UPPER",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/caption-2",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "caption/two/semibold",
    "family": "Inter",
    "fontStyle": "Semi Bold",
    "size": 10,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/caption-2",
    "weightToken": "typography/style/semibold",
    "lineHeightToken": ""
  },
  {
    "name": "caption/three/regular",
    "family": "Inter",
    "fontStyle": "Regular",
    "size": 9,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/caption-3",
    "weightToken": "typography/style/normal",
    "lineHeightToken": ""
  },
  {
    "name": "caption/three/semibold",
    "family": "Inter",
    "fontStyle": "Semi Bold",
    "size": 9,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/caption-3",
    "weightToken": "typography/style/semibold",
    "lineHeightToken": ""
  },
  {
    "name": "caption/four/regular",
    "family": "Inter",
    "fontStyle": "Regular",
    "size": 8,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/caption-4",
    "weightToken": "typography/style/normal",
    "lineHeightToken": ""
  },
  {
    "name": "caption/four/semibold",
    "family": "Inter",
    "fontStyle": "Semi Bold",
    "size": 8,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/caption-4",
    "weightToken": "typography/style/semibold",
    "lineHeightToken": ""
  },
  {
    "name": "caption/five/semibold",
    "family": "Inter",
    "fontStyle": "Semi Bold",
    "size": 6,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/caption-5",
    "weightToken": "typography/style/semibold",
    "lineHeightToken": ""
  },
  {
    "name": "mono/one/regular",
    "family": "JetBrains Mono",
    "fontStyle": "Regular",
    "size": 14,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/mono",
    "sizeToken": "text/body-1",
    "weightToken": "typography/style/normal",
    "lineHeightToken": ""
  },
  {
    "name": "mono/two/regular",
    "family": "JetBrains Mono",
    "fontStyle": "Regular",
    "size": 12,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/mono",
    "sizeToken": "text/body-2",
    "weightToken": "typography/style/normal",
    "lineHeightToken": ""
  },
  {
    "name": "mono/two/medium",
    "family": "JetBrains Mono",
    "fontStyle": "Medium",
    "size": 12,
    "lineHeight": "Auto",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/mono",
    "sizeToken": "text/body-2",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "mono/three/regular",
    "family": "JetBrains Mono",
    "fontStyle": "Regular",
    "size": 11,
    "lineHeight": "Auto",
    "letterSpacing": "5%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/mono",
    "sizeToken": "text/caption-1",
    "weightToken": "typography/style/normal",
    "lineHeightToken": ""
  },
  {
    "name": "body/two/medium",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-1",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "body/two/medium uppercase",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "UPPER",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-1",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "body/two/mono-medium",
    "family": "JetBrains Mono",
    "fontStyle": "Medium",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/mono",
    "sizeToken": "text/body-1",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "body/two/medium underline",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-1",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "body/two/mono-medium underline",
    "family": "JetBrains Mono",
    "fontStyle": "Medium",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "familyToken": "typography/mono",
    "sizeToken": "text/body-1",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "body/two/medium italic",
    "family": "Inter",
    "fontStyle": "Medium Italic",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-1",
    "weightToken": "",
    "lineHeightToken": ""
  },
  {
    "name": "body/two/semibold",
    "family": "Inter",
    "fontStyle": "Semi Bold",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-1",
    "weightToken": "typography/style/semibold",
    "lineHeightToken": ""
  },
  {
    "name": "body/two/semibold uppercase",
    "family": "Inter",
    "fontStyle": "Semi Bold",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "2.5%",
    "textCase": "UPPER",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-1",
    "weightToken": "typography/style/semibold",
    "lineHeightToken": ""
  },
  {
    "name": "body/three/bold uppercase",
    "family": "Inter",
    "fontStyle": "Bold",
    "size": 12,
    "lineHeight": "16px",
    "letterSpacing": "0%",
    "textCase": "UPPER",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-2",
    "weightToken": "typography/style/bold",
    "lineHeightToken": ""
  },
  {
    "name": "components/button/lg",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "typography/size/tailwind/sm",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "components/button/lg underline",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "familyToken": "typography/sans",
    "sizeToken": "typography/size/tailwind/sm",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "components/button/default",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "typography/size/tailwind/sm",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "components/button/default underline",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "familyToken": "typography/sans",
    "sizeToken": "typography/size/tailwind/sm",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "components/button/sm",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 12.8,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "typography/size/rem/0,8",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "components/button/sm underline",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 12.8,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "familyToken": "typography/sans",
    "sizeToken": "typography/size/rem/0,8",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "components/button/xs",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 12,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "typography/size/tailwind/xs",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "components/button/xs underline",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 12,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "familyToken": "typography/sans",
    "sizeToken": "typography/size/tailwind/xs",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "components/badge/xl/medium",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 14,
    "lineHeight": "20px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "components/badge/lg/medium",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 12,
    "lineHeight": "16px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "components/badge/md/medium",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 10,
    "lineHeight": "15px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "components/badge/sm/medium",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 10,
    "lineHeight": "15px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "components/sonner/default",
    "family": "Inter",
    "fontStyle": "Medium",
    "size": 13,
    "lineHeight": "19.5px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "",
    "weightToken": "typography/style/medium",
    "lineHeightToken": ""
  },
  {
    "name": "components/calendar/regular line-through",
    "family": "Inter",
    "fontStyle": "Regular",
    "size": 14,
    "lineHeight": "14px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "STRIKETHROUGH",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-1",
    "weightToken": "typography/style/normal",
    "lineHeightToken": ""
  },
  {
    "name": "components/calendar/regular",
    "family": "Inter",
    "fontStyle": "Regular",
    "size": 14,
    "lineHeight": "14px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-1",
    "weightToken": "typography/style/normal",
    "lineHeightToken": ""
  },
  {
    "name": "components/calendar/bold",
    "family": "Inter",
    "fontStyle": "Bold",
    "size": 14,
    "lineHeight": "14px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/sans",
    "sizeToken": "text/body-1",
    "weightToken": "typography/style/bold",
    "lineHeightToken": ""
  },
  {
    "name": "body/base/mono-regular",
    "family": "JetBrains Mono",
    "fontStyle": "Regular",
    "size": 16,
    "lineHeight": "24px",
    "letterSpacing": "0%",
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "familyToken": "typography/mono",
    "sizeToken": "typography/size/tailwind/base",
    "weightToken": "",
    "lineHeightToken": ""
  }
] as const;

export type TypographyStyle = (typeof typographyStyles)[number];

