"use client"

import { CheckboxExample } from "./checkbox-example"
import { SelectableCard as Card, SelectableTable as Table } from "./selectable-docs-shared"

export function CheckboxPatterns() { return <div className="not-prose grid gap-3 md:grid-cols-2"><Card title="Basic" value="Field + Checkbox"><CheckboxExample /></Card><Card title="Description" value="FieldContent"><CheckboxExample text="description" /></Card><Card title="Choice Card" value="appearance=contained"><CheckboxExample appearance="contained" checked /></Card><Card title="Group" value="4 options"><CheckboxExample amount={4} checked /></Card></div> }
export function CheckboxPlacement() { return <div className="not-prose grid gap-3 md:grid-cols-2"><Card title="Text right" value="control → label"><CheckboxExample /></Card><Card title="Text left" value="label → control"><CheckboxExample textSide="left" /></Card></div> }
export function CheckboxStates() { return <div className="not-prose grid gap-3 sm:grid-cols-3"><Card title="Unchecked" value="checked=false"><CheckboxExample /></Card><Card title="Checked" value="checked=true"><CheckboxExample checked /></Card><Card title="Invalid" value="aria-invalid"><CheckboxExample state="error" /></Card><Card title="Disabled" value="disabled"><CheckboxExample state="disabled" /></Card></div> }
const geometry = [["Control", "size-4", "16 × 16px", "Oficial shadcn/ui / Figma"],["Radius", "rounded-[4px]", "4px", "Figma"],["Control gap", "gap-3", "12px", "Figma"],["Choice Card", "p-2.5", "10px", "Oficial shadcn/ui FieldLabel"],["Label", "text-sm / leading-5 / font-medium", "14px / 20px / 500", "Token tipográfico"]] as const
const styles = [["Unchecked", "transparent", "--input", "—"],["Checked", "--primary", "--primary", "--primary-foreground"],["Invalid", "transparent", "--destructive", "—"],["Focus", "Por estado", "--ring", "ring-3 / 50%"],["Disabled", "Por estado", "Por estado", "opacity-50"]] as const
export function CheckboxSpecifications() { return <div className="not-prose grid gap-6"><section><h3 style={{ margin: "0 0 12px", fontSize: 16, fontWeight: 600, lineHeight: "24px" }}>Tamaño y espaciado</h3><Table columns={["Parte", "Tailwind", "Valor", "Origen"]} rows={geometry} /></section><section><h3 style={{ margin: "0 0 12px", fontSize: 16, fontWeight: 600, lineHeight: "24px" }}>Estados y tokens</h3><Table columns={["Estado", "Fondo", "Borde", "Contenido"]} rows={styles} /></section></div> }
