"use client"

import { RadioGroupExample } from "./radio-group-example"
import { SelectableCard as Card, SelectableTable as Table } from "./selectable-docs-shared"

export function RadioGroupPatterns() { return <div className="not-prose grid gap-3 md:grid-cols-2"><Card title="Basic" value="RadioGroup + Item"><RadioGroupExample /></Card><Card title="Description" value="FieldContent"><RadioGroupExample text="description" /></Card><Card title="Choice Cards" value="appearance=contained"><RadioGroupExample appearance="contained" /></Card><Card title="Six options" value="amount=6"><RadioGroupExample amount={6} /></Card></div> }
export function RadioGroupPlacement() { return <div className="not-prose grid gap-3 md:grid-cols-2"><Card title="Text right" value="control → label"><RadioGroupExample amount={2} /></Card><Card title="Text left" value="label → control"><RadioGroupExample amount={2} textSide="left" /></Card></div> }
export function RadioGroupStates() { return <div className="not-prose grid gap-3 sm:grid-cols-3"><Card title="Selected" value="defaultValue"><RadioGroupExample amount={2} /></Card><Card title="Unselected" value="defaultValue=undefined"><RadioGroupExample amount={2} selected={false} /></Card><Card title="Invalid" value="aria-invalid"><RadioGroupExample amount={2} state="error" /></Card><Card title="Disabled" value="disabled"><RadioGroupExample amount={2} state="disabled" /></Card></div> }
const geometry = [["Item", "size-4", "16 × 16px", "Oficial shadcn/ui / Figma"],["Indicator", "size-2", "8 × 8px", "Oficial shadcn/ui"],["Option gap", "gap-3", "12px", "Figma"],["Group gap", "gap-3", "12px", "Figma"],["Label", "text-sm / leading-5 / font-medium", "14px / 20px / 500", "Token tipográfico"]] as const
const styles = [["Unchecked", "transparent", "--input", "—"],["Checked", "--primary", "--primary", "--primary-foreground"],["Invalid", "transparent", "--destructive", "—"],["Focus", "Por estado", "--ring", "ring-3 / 50%"],["Disabled", "Por estado", "Por estado", "opacity-50"]] as const
export function RadioGroupSpecifications() { return <div className="not-prose grid gap-6"><section><h3 style={{ margin: "0 0 12px", fontSize: 16, fontWeight: 600, lineHeight: "24px" }}>Tamaño y espaciado</h3><Table columns={["Parte", "Tailwind", "Valor", "Origen"]} rows={geometry} /></section><section><h3 style={{ margin: "0 0 12px", fontSize: 16, fontWeight: 600, lineHeight: "24px" }}>Estados y tokens</h3><Table columns={["Estado", "Fondo", "Borde", "Indicador"]} rows={styles} /></section></div> }
