"use client"

import { SwitchExample } from "./switch-example"
import { SelectableCard as Card, SelectableTable as Table } from "./selectable-docs-shared"

export function SwitchPatterns() { return <div className="not-prose grid gap-3 md:grid-cols-2"><Card title="Basic" value="Field + Switch"><SwitchExample /></Card><Card title="Description" value="FieldContent"><SwitchExample text="description" /></Card><Card title="Choice Card" value="appearance=contained"><SwitchExample appearance="contained" checked /></Card></div> }
export function SwitchPlacement() { return <div className="not-prose grid gap-3 md:grid-cols-2"><Card title="Text right" value="control → label"><SwitchExample /></Card><Card title="Text left" value="label → control"><SwitchExample textSide="left" /></Card></div> }
export function SwitchSizes() { return <div className="not-prose grid gap-3 md:grid-cols-2"><Card title="Small" value="size=sm"><SwitchExample size="sm" checked /></Card><Card title="Default" value="size=default"><SwitchExample checked /></Card></div> }
export function SwitchStates() { return <div className="not-prose grid gap-3 sm:grid-cols-3"><Card title="Off" value="checked=false"><SwitchExample /></Card><Card title="On" value="checked=true"><SwitchExample checked /></Card><Card title="Invalid" value="aria-invalid"><SwitchExample state="error" /></Card><Card title="Disabled" value="disabled"><SwitchExample state="disabled" /></Card></div> }
const geometry = [["sm track", "w-6 / h-[14px]", "24 × 14px", "Figma"],["sm thumb", "size-3", "12 × 12px", "Figma"],["default track", "w-8 / h-[18.4px]", "32 × 18.4px", "Figma"],["default thumb", "size-4", "16 × 16px", "Figma"],["Control gap", "gap-2", "8px", "Figma"],["Label", "text-sm / leading-5 / font-medium", "14px / 20px / 500", "Token tipográfico"]] as const
const styles = [["Off", "--input", "--background", "transparent"],["On", "--primary", "--background", "transparent"],["Invalid", "Por estado", "Por estado", "--destructive + ring"],["Focus", "Por estado", "Por estado", "--ring / 50%"],["Disabled", "Por estado", "Por estado", "opacity-50"]] as const
export function SwitchSpecifications() { return <div className="not-prose grid gap-6"><section><h3 style={{ margin: "0 0 12px", fontSize: 16, fontWeight: 600, lineHeight: "24px" }}>Tamaño y espaciado</h3><Table columns={["Parte", "Tailwind", "Valor", "Origen"]} rows={geometry} /></section><section><h3 style={{ margin: "0 0 12px", fontSize: 16, fontWeight: 600, lineHeight: "24px" }}>Estados y tokens</h3><Table columns={["Estado", "Track", "Thumb", "Borde · tratamiento"]} rows={styles} /></section></div> }
