"use client"

import type { ReactNode } from "react"

import { ToastExample, type ToastStatus } from "./toast-example"

function Code({ children }: { children: string }) { return <code className="inline-flex min-h-6 items-center rounded bg-muted px-1.5 py-1 text-foreground" style={{ fontSize: 10, lineHeight: 1 }}>{children}</code> }
function Card({ title, value, children }: { title: string; value: string; children: ReactNode }) { return <article className="overflow-hidden rounded-lg border border-border bg-card"><div className="flex min-h-40 items-center justify-center overflow-hidden bg-background p-6">{children}</div><div className="flex min-h-14 items-center justify-between gap-3 border-t border-border px-4"><strong className="truncate text-card-foreground" style={{ fontSize: 14, lineHeight: "20px" }}>{title}</strong><Code>{value}</Code></div></article> }

const statuses: readonly [string, ToastStatus][] = [["Success", "success"], ["Warning", "warning"], ["Error", "error"], ["Info", "info"], ["Brand neutral", "brand-neutral"], ["Neutral", "neutral"]]

export function ToastStatuses() { return <div className="not-prose grid gap-3 md:grid-cols-2">{statuses.map(([title, status]) => <Card key={status} title={title} value={`type=${status}`}><ToastExample status={status} preview /></Card>)}</div> }
export function ToastCompositions() { return <div className="not-prose grid gap-3 md:grid-cols-2"><Card title="Sin icono" value="showIcon=false"><ToastExample showIcon={false} preview /></Card><Card title="Con descripción" value="description"><ToastExample showDescription preview /></Card><Card title="Con acción" value="actionProps"><ToastExample showAction preview /></Card><Card title="Con cierre" value="ToastClose"><ToastExample showClose preview /></Card></div> }
export function ToastBehaviors() { return <div className="not-prose grid gap-3 md:grid-cols-2"><Card title="Promise" value="toast.promise"><ToastExample behavior="promise" /></Card><Card title="Stacking" value="limit + stack"><ToastExample behavior="stack" /></Card></div> }

const statusRows = [["success", "--success-light", "--success-light-foreground", "--success-light-border", "CircleCheckIcon"], ["warning", "--warning-light", "--warning-light-foreground", "--warning-light-border", "TriangleAlertIcon"], ["error", "--error-light", "--error-light-foreground", "--error-light-border", "CircleXIcon"], ["info", "--info-light", "--info-light-foreground", "--info-light-border", "InfoIcon"], ["brand-neutral", "--background", "--foreground", "--border", "CircleCheckIcon"], ["neutral", "--card", "--foreground", "--border", "CircleCheckIcon"]] as const
const geometryRows = [["Toast", "356px", "54px base · auto con extras", "16px", "12px · gap-3", "18px · rounded-2xl"], ["Icon", "16px", "16px", "0px", "—", "—"], ["Title", "intrínseco", "19.5px", "0px", "—", "—"]] as const
function Table({ columns, rows }: { columns: readonly string[]; rows: readonly (readonly string[])[] }) { return <div className="not-prose overflow-x-auto rounded-lg border border-border bg-card"><table style={{ width: "100%", minWidth: 760, borderCollapse: "collapse", tableLayout: "fixed" }}><thead><tr style={{ background: "var(--muted)" }}>{columns.map(column => <th key={column} style={{ padding: "11px 16px", border: 0, borderBottom: "1px solid var(--border)", color: "var(--muted-foreground)", fontSize: 11, fontWeight: 600, letterSpacing: ".04em", lineHeight: 1.4, textAlign: "left", textTransform: "uppercase", verticalAlign: "middle" }}>{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row[0]} style={{ background: index % 2 ? "color-mix(in srgb, var(--muted) 30%, transparent)" : "transparent" }}>{row.map((value, cell) => <td key={`${row[0]}-${cell}`} style={{ height: 52, padding: "10px 16px", border: 0, borderBottom: index === rows.length - 1 ? 0 : "1px solid var(--border)", color: "var(--foreground)", fontSize: 12, lineHeight: 1.4, verticalAlign: "middle" }}>{cell === 0 || value.startsWith("--") ? <Code>{value}</Code> : value}</td>)}</tr>)}</tbody></table></div> }
export function ToastSpecifications() { return <div className="not-prose grid gap-6"><section><h3 style={{ margin: "0 0 12px", fontSize: 16, fontWeight: 600, lineHeight: "24px" }}>Color por estado</h3><Table columns={["Estado", "Fondo", "Texto", "Borde", "Icono"]} rows={statusRows} /></section><section><h3 style={{ margin: "0 0 12px", fontSize: 16, fontWeight: 600, lineHeight: "24px" }}>Tamaño y espaciado</h3><Table columns={["Elemento", "Ancho", "Alto", "Padding", "Gap", "Radio"]} rows={geometryRows} /></section><section><h3 style={{ margin: "0 0 12px", fontSize: 16, fontWeight: 600, lineHeight: "24px" }}>Tipografía y elevación</h3><Table columns={["Elemento", "Fuente", "Tamaño", "Line height", "Peso", "Sombra"]} rows={[["Title", "--brand-font-sans", "13px", "19.5px", "500", "0 4px 12px rgb(0 0 0 / 10%)"]]} /></section></div> }
