"use client"

import type { ReactNode } from "react"

import { ToastExample, type ToastStatus } from "./toast-example"

function Code({ children }: { children: string }) { return <code className="inline-flex min-h-6 items-center rounded bg-muted px-1.5 py-1 text-foreground text-(length:--docs-code-font-size) leading-none">{children}</code> }
function Card({ title, value, children }: { title: string; value: string; children: ReactNode }) { return <article className="overflow-hidden rounded-lg border border-border bg-card"><div className="sb-unstyled flex min-h-40 items-center justify-center overflow-hidden bg-background p-6">{children}</div><div className="flex min-h-14 items-center justify-between gap-3 border-t border-border px-4"><strong className="truncate text-card-foreground text-sm leading-5">{title}</strong><Code>{value}</Code></div></article> }

const statuses: readonly [string, ToastStatus][] = [["Success", "success"], ["Warning", "warning"], ["Error", "error"], ["Info", "info"], ["Brand neutral", "brand-neutral"], ["Neutral", "neutral"]]

export function ToastStatuses() { return <div className="not-prose grid gap-3 lg:grid-cols-2">{statuses.map(([title, status]) => <Card key={status} title={title} value={`type=${status}`}><ToastExample status={status} preview /></Card>)}</div> }
export function ToastCompositions() { return <div className="not-prose grid gap-3 lg:grid-cols-2"><Card title="Sin icono" value="showIcon=false"><ToastExample showIcon={false} preview /></Card><Card title="Con descripción" value="description"><ToastExample showDescription preview /></Card><Card title="Con acción" value="actionProps"><ToastExample showAction preview /></Card><Card title="Con cierre" value="ToastClose"><ToastExample showClose preview /></Card></div> }
export function ToastBehaviors() { return <div className="not-prose grid gap-3 lg:grid-cols-2"><Card title="Promise" value="toast.promise"><ToastExample behavior="promise" /></Card><Card title="Stacking" value="limit + stack"><ToastExample behavior="stack" /></Card></div> }

const statusRows = [["success", "--success-light", "--success-light-foreground", "--success-light-border", "CircleCheckIcon"], ["warning", "--warning-light", "--warning-light-foreground", "--warning-light-border", "TriangleAlertIcon"], ["error", "--error-light", "--error-light-foreground", "--error-light-border", "CircleXIcon"], ["info", "--info-light", "--info-light-foreground", "--info-light-border", "InfoIcon"], ["brand-neutral", "--background", "--foreground", "--border", "CircleCheckIcon"], ["neutral", "--card", "--foreground", "--border", "CircleCheckIcon"]] as const
const geometryRows = [["Toast", "--toast-width", "--toast-compact-height · auto con extras", "p-4", "gap-3", "rounded-2xl"], ["Icon", "size-4", "size-4", "p-0", "—", "—"], ["Title", "intrínseco", "--toast-title-line-height", "p-0", "—", "—"]] as const
function Table({ columns, rows }: { columns: readonly string[]; rows: readonly (readonly string[])[] }) { return <div className="not-prose overflow-x-auto rounded-lg border border-border bg-card"><table className="docs-spec-table min-w-3xl"><thead><tr>{columns.map(column => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((value, cell) => <td key={`${row[0]}-${cell}`}>{cell === 0 || value.startsWith("--") ? <Code>{value}</Code> : value}</td>)}</tr>)}</tbody></table></div> }
export function ToastSpecifications() { return <div className="not-prose grid gap-6"><section><h3 className="mb-3 text-base leading-6 font-semibold text-foreground">Color por estado</h3><Table columns={["Estado", "Fondo", "Texto", "Borde", "Icono"]} rows={statusRows} /></section><section><h3 className="mb-3 text-base leading-6 font-semibold text-foreground">Tamaño y espaciado</h3><Table columns={["Elemento", "Ancho", "Alto", "Padding", "Gap", "Radio"]} rows={geometryRows} /></section><section><h3 className="mb-3 text-base leading-6 font-semibold text-foreground">Tipografía y elevación</h3><Table columns={["Elemento", "Fuente", "Tamaño", "Line height", "Peso", "Sombra"]} rows={[["Title", "--brand-font-sans", "--toast-title-font-size", "--toast-title-line-height", "--font-weight-medium", "--toast-shadow"]]} /></section></div> }
